### PR TITLE
Replace Erlang unicode with iconv in hot code path

### PR DESCRIPTION
**Pull request by naag**
Hi all, we use `tds` to query datasets with lots of `NVARCHAR(MAX)` data and discovered a performance issue in `Tds.Types.decode_nchar/1`. By replacing Erlang `unicode` with the `iconv` hex, the performance was massively improved without any other code changes (tests are passing).

### CODE REVIEW

**Comment by naag** [comment]
Please excuse the big diff on `mix.lock`, this happened due to us using a different version of Elixir it seems.

**Comment by mjaric** [comment]
Hi, thank you for contributing! I would like to check if there are any performance issues in case nif is accessed from more than one process. 

Did you try using/compiling this in Windows OS?

**Comment by naag** [comment]
Actually, that's a good point - we've just been using Linux.

**Comment by mjaric** [comment]
this is solved with rust encoding NIF in [support-1.1](https://github.com/livehelpnow/tds/commit/d07582655ca16dd5dfc01f8abe5612142c5e16fd) tho requires some additional work for input parameters

**Comment by mjaric** [comment]
closed in favor to #86

**Pull request closed without merging**
